# Generated by Django 5.0.1 on 2024-01-31 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_watchlist_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='blog.watchlist')),
            ],
        ),
    ]
