# Generated by Django 5.0.1 on 2024-02-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_watchlist_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='stars',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
