# Generated by Django 5.0.1 on 2024-02-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_watchlist_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='stars',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
