# Generated by Django 5.0.1 on 2024-02-01 05:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_watchlist_stars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('stars', models.IntegerField()),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
