# Generated by Django 5.0.1 on 2024-02-01 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_review_stars_review_active_review_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='stars',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
