# Generated by Django 5.0.1 on 2024-02-16 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_watchlist_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='image',
        ),
    ]
